site_name: 2º DAM - Programación Multimedia y Desarrollo móvil - Curso 26/27
site_url: https://jssdocente.github.io/pmdm2627d
use_directory_urls: false

nav:
  - "Inicio": "index.md"
  - "Android":
      - "Inicio": temas/00-android/index.md
      - "Entorno de desarrollo (IDE)":
          - "IntelliJ IDEA para Móvil": temas/00-android/00-ide-intellij/index.md
      - "El lenguaje kotlin":
          - "Introducción": temas/00-android/00-kotlin/index.md
          - "Variables": temas/00-android/00-kotlin/11-variables-tipos-datos.md
          - "Expresiones vs Sentencias": temas/00-android/00-kotlin/12-expresiones-vs-sentencias.md
          - "When": temas/00-android/00-kotlin/12.1-when.md
          - "Funciones y lambdas": temas/00-android/00-kotlin/13-funciones-lambdas.md
          - "Null safety": temas/00-android/00-kotlin/14-null-safety.md
          - "Colecciones":
              - "Arrays": temas/00-android/00-kotlin/41-arrays.md
              - "Listas": temas/00-android/00-kotlin/42-listas.md
              - "Maps": temas/00-android/00-kotlin/43-maps.md
              - "Sets": temas/00-android/00-kotlin/44-sets.md
          - "POO": temas/00-android/00-kotlin/21-poo.md
          - "Objetos anónimos": temas/00-android/00-kotlin/22-objetos-anonimos.md
          - "Data classes": temas/00-android/00-kotlin/23-data-classes.md
          - "Enum classes": temas/00-android/00-kotlin/24-enum-classes.md
          - "Genéricos": temas/00-android/00-kotlin/25-genericos.md
          - "Clases selladas": temas/00-android/00-kotlin/26-sealed-classes.md
          - "Scope functions": temas/00-android/00-kotlin/31-scope-functions.md
          - "Corrutinas": temas/00-android/00-kotlin/52-corrutinas-sencillo.md
      - "Herramientas Proyecto Android":
          - "Gradle": "temas/00-android/00-tools/01-gradle-agp-estructura.md"
          - "Build-gradle": "temas/00-android/00-tools/02-build-gradle.md"
          - "Fichero Manifest": "temas/00-android/00-tools/03-android-manifest.md"
          - "Matriz de Compatibilidad": "temas/00-android/00-tools/04-matriz-compatibilidad.md"

      - "Jetpack Compose":
          - "Introducción": temas/00-android/00-compose/index.md
          - "Funciones componibles": temas/00-android/00-compose/21-composable-functions.md
          - "Gestión del estado": temas/00-android/00-compose/22-state-management.md
          - "Listas": temas/00-android/00-compose/23-listas-cuadriculas.md
          - "Navegación Rutas": temas/00-android/00-compose/24-navegacion-rutas.md
          - "Material Design": temas/00-android/00-compose/25-material-design.md
          - "Glosario": temas/00-android/00-compose/99-glosario-android.md

    # - "Ciclo de Vida aplicación Android": temas/00-android/01-ciclo-vida-app.md
    # - "Arquitecturas en Android": temas/00-android/02-arquitectura.md
    # - "Capa de UI": temas/00-android/02-capa-ui.md
  #     - ""
  - "UT1 - Visión General y Entorno de desarrollo": temas/01/index.md
  # - "UT2 - Programación de aplicaciones de móviles con Android":
  #   - "Inicio": temas/02/index.md
  #   - "2.1. Primeros pasos": temas/02/2.1-primeros-pasos.md
  #   - "2.2. Ciclo de Vida": temas/02/2.2-ciclo-vida-app.md
  #   - "2.3. Primera aplicación": temas/02/2.3-primera-app.md
  #   - "2.4. Gestión del estado": temas/02/2.4-gestion-estado.md
  #   - "2.5. Mejorando el código": temas/02/2.5-mejorando-codigo.md
  #   - "2.6. Manejo de listas": temas/02/2.6-mostrar-listas.md

  # - "UT3 - Interfaz de Usuario":
  #   - "Inicio": temas/03/index.md
  #   - "3.1. Introducción": temas/03/3.1-intro.md
  #   - "3.2. Temas": temas/03/3.2-temas.md
  #   - "3.3. Arquitectura":
  #     - "3.3.1. Introducción": temas/03/3.3-arquitectura.md
  #     - "3.3.2. Capa de UI": temas/03/3.3.2-arquitectura.capa-ui
  #     - "3.3.3. Capas Datos/Dominio": temas/03/3.3.3-arquitectura.capa-datos.md
  #     - "3.3.4. Clean Architecture":
  #       - "Capa de Dominio": temas/03/3.3.3.2-CapaDominio-es.md
  #       - "Capa de Datos": temas/03/3.3.3.3-CapaDatos-es.md

  # - "UT4 - Persistencia":
  #   - "Introducción": temas/04/4.0-persistencia.md
  #   - "4.1. Room": temas/04/4.1-room.md
  #   - "4.2. Conexión a Internet": temas/04/4.2-conexion-internet.md
  #   #- "3.3. Arquitectura": temas/03/3.3-arquitectura.md

  # - "Proyecto Guía":
  #   - "Introducción": temas/proyectos/GameVault/index.md
  #   - "1. Configuración proyecto": temas/proyectos/GameVault/01-configuracion-proyecto.md
  #   - "2. Pantalla Login": temas/proyectos/GameVault/02-LoginScreen.md
  #   - "3. Preferencias": temas/proyectos/GameVault/03-Preferences.md
  #   - "4. Registro y logout": temas/proyectos/GameVault/04-Register-logout.md
  #   - "5. HomeScreen": temas/proyectos/GameVault/05-HomeScreen.md
  #   - "6. Detalles de un juego": temas/proyectos/GameVault/06-DetailScreen.md
  #   - "7. Persistencia con Room": temas/proyectos/GameVault/07-RoomPersistence.md
  #   - "8. Biblioteca y detalles avanzados": temas/proyectos/GameVault/08-LibraryAndDetailAdvanced.md
  #   - "9. Inyección de dependencias con Koin": temas/proyectos/GameVault/09-DI-Koin.md
  #   - "10. Autenticación con Firebase": temas/proyectos/GameVault/10-Auth-firebase.md
  #   - "11. Autenticación con Google": temas/proyectos/GameVault/11-Auth-google.md
  #   - "12. Implementar nueva Feature": temas/proyectos/GameVault/12-implementar-nueva-feature.md
  #   - "13. Sistema de Logging": temas/proyectos/GameVault/13-Sistema-logging.md
  #   - "14. Consumo de APIs": temas/proyectos/GameVault/14-Consumo-apis.md
  #   - "15. Soporte multiidioma": temas/proyectos/GameVault/15-Soporte-multilenguaje.md
  #   - "16. Compilación y Generación de Artefactos": temas/proyectos/GameVault/16-generar-artefactos.md

  #- "Paso 1": temas/proyectos/GameVault/01-configuracion-proyecto.md

  #   - "1. Instalar Laravel": "temas/07/01.instalar-laravel.md"
  #   - "2. Configurar Tailwind": "temas/07/02.configurar-tailwind.md"
  #   - "3. Layouts con Blade": "temas/07/03.layouts-con-blade.md"
  #   - "4. Primer componente": "temas/07/04.primer-componente.md"
  #   - "5. Estilando componente": "temas/07/05.estilando-nav-link.md"
  #   - "6. Pasar datos a las vistas": "temas/07/06.pasar-datos-vista-y-rutas.md"
  #   - "7. Autloading y namespaces": "temas/07/07.autoloading-namespaces-y-models.md"
  #   - "8. Introducción a las migraciones": "temas/07/08.intro-migraciones.md"
  #   - "9. Introducción a Eloquent": "temas/07/09.intro-eloquent.md"
  #   - "10. Eloquent: Factorias": "temas/07/10.eloquent-factories.md"
  #   - "11. Eloquent: relaciones básicas": "temas/07/11.eloquent-relations-basic.md"
  #   - "12. Eloquent: relación many-to-many": "temas/07/12.eloquent-relations-many-to-many.md"
  #   - "13. Eloquent: relación many-has-many-throught": "temas/07/13.eloquent-relations-has-many-throught.md"
  # - "8.- Frameworks PHP - Laravel avanzado":
  #   - "Introducción": temas/08/index.md
  #   - "14. Database Seeders": "temas/08/14.database-seeders.md"
  #   - "15. Formularios con Laravel y CRSF": "temas/08/15.forms-csrf.md"
  #   - "16. Validación": "temas/08/16.forms-always-validate.md"
  #   - "17. Formularios CRUD": "temas/08/17.forms-edit-update-delete.md"
  #   - "18. Mejorando las rutas": "temas/08/18.mejorar-rutas.md"
  #   - "19. Autenticación: crear sistema": "temas/08/19.create-login-register-system.md"
  #   - "20. Autorización: proteger rutas": "temas/08/20.proteger-rutas-middleware.md"
  #   - "21. Informando al usuario": "temas/08/21.flash-messages.md"
  #   - "22. Control y Gestión de excepciones": "temas/08/22.Manejando-excepciones.md"

  # - "8.- Servicios REST": "09rest.md"
  # - "Anexo":
  #   - "Anexo I. Arquitecturas Web": "extra/ArquitecturasWebExtendido.md"

  # - "Guias":
  #   - "Configuración entorno desarrollo PHP con Laravel Herd": "extra/guias/02.config_devenv_laravel_herd.md"

theme:
  language: es
  favicon: imagenes/favicon.png
  name: "material"
  palette:
    - scheme: default
      primary: light blue
      accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo noche
    - scheme: slate
      primary: light blue
      accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo día
  icon:
    annotation: material/plus-circle
  font:
    text: Roboto
    code: Roboto Mono
  logo: "imagenes/logofp.png"
  features:
    - header.autohide
    # - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - navigation.top
    - content.code.annotate
    #- navigation.expand
    - navigation.path
    - content.tooltips

  custom_width: false

extra:
  search:
    language: "es"
  social:
    - icon: material/email-edit
      link: mailto:<jssgarcia.docente@gmail.com>
  #analytics:
  #provider: google
  #property: G-X6D0LR7TC8
extra_css:
  - extra/css/extra.css

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: 2026-2027 Jesús García - Licencia CC BY-NC-SA
